### ISSUE TITLE
graph ql API 테스트용 코드

### ISSUE THREAD

**Issue by kimsehwan96** [kimsehwan96/car-iot-platform-from-kpu#39]
통계 데이터를 react client에서 사용하기 위해서는, Dynamodb에 있는 값을 리턴 해 줄 수 있는 graphql 인터페이스가 필요합니다. 

Appsync를 이용해 구현 할 예정이며, 

구현해야 하는 내용은

graphql 스키마, 
graphql 리졸버 입니다. 

스키마는 일종에 데이터가 어떤 형식으로 구조가 되어있는지 정의 해주는 부분이고,

리졸버는 실제 쿼리문이 왔을 때 어떻게 처리해야하는지에 대한 내용이 서술된 부분입니다. 

```graphql
schema {
    query: Query
    mutation: Mutation
}

type Query{
    getProfile(userID: String!): Profile
}

type Mutation {
    createProfile(input: ProfileInput): Profile
    deleteProfile(input: deleteProfileInput): Profile
    updateProfile(input: updateProfileInput): Profile
}

type Profile {
    userID: ID!
    fields: [String]
    carType: String
    madeAt: AWSDateTime
    updatedAt: AWSDateTime
}
```
위와 같은 양식이 graphql 스키마이고, 실제 객체들을 정의하는 부분입니다.

resolver는 쿼리나 뮤테이션 필드(명령)이 들어왔을때 어떤 db에 접근하고, 어떻게 리턴해줄 것인지에 대한 내용들을 정의하는 부분입니다. 

```vtl
{
  "version" : "2017-02-28",
  "operation" : "PutItem",
  "key" : {
    "userId": $util.toJson($ctx.args.input.userID),
    "madeAt" : $util.dynamodb.toDynamoDBJson($util.time.nowISO8601())
  },
  "attributeValues" : $util.dynamodb.toMapValuesJson($ctx.args.input)
}
```
위 예제는 createProfile 명령이 들어왔을때 서버에서 어떻게 응답할지를 정의 한 내용입니다. 

```yml
service: "appsync-api-cariot-dev"

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: cariot-api-dev
    authenticationType: API_KEY
    mappingTemplatesLocation: mapping-templates
    schema: 
      - schema.gql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: ProfileTable
        config:
          tableName: ProfileTable

      - dataSource: ProfileTable
        type: Mutation 
        field: createProfile
        request: Profile.createProfile.request.vtl
        response: Profile.createProfile.response.vtl
```

위는 serverless yml입니다. 이렇게 어떤 명령어가 들어올때 어떤 vtl을 사용할 것인지 정의 해줄 수 있습니다.
